matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
# bison/flex specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bison ; export PATH=/usr/local/opt/bison/bin:$PATH ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex; export PATH=/usr/local/opt/flex/bin:$PATH ; fi
# End of bison/flex specific part
#-----------------------
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - git clone https://github.com/quicky2000/parameter_manager.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build; cd build; generate_makefile vcd_parser_engine ; make test; fi
  - cd $MY_LOCATION ; mkdir cmake_build ; cd cmake_build ; cmake $QUICKY_REPOSITORY/vcd_parser_engine
  - make
  - ./vcd_parser_engine $QUICKY_REPOSITORY/vcd_parser_engine/test_cases/trace.vcd
#EOF
